version: '2.0'

services:
        nginx:
                restart: always
                image: nginx:1.11.6-alpine
                ports:
                        - 8080:8080
                        - 443:443
                volumes:
                        - ./conf.d:/etc/nginx/conf.d
                        - ./log:/var/log/nginx
                        - ./dist:/usr/share/nginx/html
